// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARijXxnZA7aLr8wftjijqB1X2nvOSZgp8',
    appId: '1:3185423692:web:3e89923950da6a671a0be9',
    messagingSenderId: '3185423692',
    projectId: 'dht-471f6',
    authDomain: 'dht-471f6.firebaseapp.com',
    storageBucket: 'dht-471f6.firebasestorage.app',
    measurementId: 'G-1ZQKL8MNHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4-3OP6TaI-CjNXYPqTdHBQW5XfJAyaSI',
    appId: '1:3185423692:android:62502a4596ec5f511a0be9',
    messagingSenderId: '3185423692',
    projectId: 'dht-471f6',
    storageBucket: 'dht-471f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2s_QG390Z8oTOde6EbfAjOSjuJeAK5F0',
    appId: '1:3185423692:ios:9542ac01fb4f9e601a0be9',
    messagingSenderId: '3185423692',
    projectId: 'dht-471f6',
    storageBucket: 'dht-471f6.firebasestorage.app',
    iosBundleId: 'com.example.dailyHabitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2s_QG390Z8oTOde6EbfAjOSjuJeAK5F0',
    appId: '1:3185423692:ios:9542ac01fb4f9e601a0be9',
    messagingSenderId: '3185423692',
    projectId: 'dht-471f6',
    storageBucket: 'dht-471f6.firebasestorage.app',
    iosBundleId: 'com.example.dailyHabitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARijXxnZA7aLr8wftjijqB1X2nvOSZgp8',
    appId: '1:3185423692:web:1e46b98d08b3f4c31a0be9',
    messagingSenderId: '3185423692',
    projectId: 'dht-471f6',
    authDomain: 'dht-471f6.firebaseapp.com',
    storageBucket: 'dht-471f6.firebasestorage.app',
    measurementId: 'G-78ZE2C5WCR',
  );
}
